spring:
  # 设置文件上传大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  # 404请求时抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  # 取消默认增加映射，如 /error
  resources:
    add-mappings: false
  # 激活哪个环境
  profiles:
    active: gauss
  # 日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    timezone: GMT+8
server:
  port: 8088

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
# 日志级别
logging:
  level:
    cn.edu.bit.dnd.mapper: warn
