server:
  port: 10010
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 43.138.10.134:8848 # nacos地址
    gateway:
      routes:
        - id: bookdetail-service # 路由标示，必须唯一
          uri: lb://bookdetailservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/detail/** # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: borrowinfo-service
          uri: lb://borrrowinfoservice
          predicates:
            - Path=/borrow/**
        - id: other-service
          uri: lb://otherservice
          predicates:
            - Path=/other/**
      default-filters:
        - AddRequestHeader=Truth, book is freaking awesome!