server:
  port: 8091
spring:
  application:
    name: bookservice # 服务名称
  #  配置数据源
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://120.46.153.45:26000/book?currentSchema=book
    username: fan
    password: SIsi04200521
  cloud:
    nacos:
      server-addr: localhost:8848 # Nacos地址
  # 设置文件上传大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  # 404请求时抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  # 取消默认增加映射，如 /error
  resources:
    add-mappings: false
  # 日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    timezone: GMT+8

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml

bookdetailservice: # 给某个微服务配置负载均衡规则
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule # 负载均衡规则
ribbon:
  eager-load:
    enabled: true
    clients:
      - bookdetailservice

# 日志级别
logging:
  level:
    com.bit.book.mapper: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
