spring:
  #  配置数据源
  datasource:
    driver-class-name: org.postgresql.Driver
    # url: jdbc:postgresql://123.249.84.58:26000/book?currentSchema=book
    url: jdbc:postgresql://192.168.231.131:26000/book?currentSchema=book
    username: fan
    password: SIsi04200521
  # 设置文件上传大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  # 404请求时抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  # 取消默认增加映射，如 /error
  resources:
    add-mappings: false
  # 日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    timezone: GMT+8
server:
  port: 8093

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml

# 日志级别
logging:
  level:
    cn.edu.bit.dnd.mapper: warn
